package model

import "time"

// Message represents an encrypted message stored in the relay.
// The server treats the Payload as an opaque blob — all encryption/decryption
// happens client-side. The relay is intentionally "dumb".
type Message struct {
	ID        string     `json:"id"`        // UUID, auto-generated by server
	To        string     `json:"to"`        // Recipient wallet address (the lookup key)
	From      string     `json:"from"`      // Sender wallet address
	Payload   string     `json:"payload"`   // Encrypted data (base64 string, opaque to server)
	CreatedAt time.Time  `json:"createdAt"` // Timestamp when message was stored
	ExpiresAt *time.Time `json:"expiresAt"` // Auto-purge time (nil = forever, only manual delete)
}

// CreateMessageRequest is the expected JSON body for POST /api/messages.
type CreateMessageRequest struct {
	To      string `json:"to"`
	From    string `json:"from"`
	Payload string `json:"payload"`
}

// Validate checks that all required fields are present and non-empty.
func (r *CreateMessageRequest) Validate() string {
	if r.To == "" {
		return "field 'to' is required"
	}
	if r.From == "" {
		return "field 'from' is required"
	}
	if r.Payload == "" {
		return "field 'payload' is required"
	}
	return ""
}
